/**
 * Command: init, install-browsers — Project setup utilities.
 */
import { existsSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { execSync } from 'node:child_process';
import pc from 'picocolors';
import {
  renderCommand,
  renderError,
  renderSuccess,
  createSpinner,
  confirmPrompt,
} from '../utils/format.js';

export async function installBrowsersCommand(): Promise<void> {
  console.error(`\n  ${pc.bold('Installing Browser Engines')}\n`);
  const spinner = createSpinner('Installing Chromium...');
  try {
    execSync('npx playwright install chromium', { stdio: 'pipe', timeout: 120000 });
    spinner.succeed('Chromium installed successfully');
  } catch {
    spinner.fail('Failed to install Chromium');
    console.error(
      `  ${pc.yellow('→')} Try running: ${renderCommand('npx playwright install chromium')}`,
    );
  }
  console.error(`\n  ${pc.green('✓')} Browser installation complete.\n`);
}

export async function initCommand(): Promise<void> {
  console.error(`\n  ${pc.bold('Initialize Fennec Configuration')}\n`);

  const configFile = resolve('./fennec.config.yaml');
  if (existsSync(configFile)) {
    const overwrite = await confirmPrompt(
      `${pc.yellow('fennec.config.yaml')} already exists. Overwrite?`,
      false,
    );
    if (!overwrite) {
      console.error(`  ${pc.dim('Cancelled.')}\n`);
      return;
    }
  }

  const spinner = createSpinner('Generating configuration...');

  const config = `# Fennec Configuration
# Generated by 'fennec init'

# ── Tool Categories exposed to AI agents via MCP ──
# These are the tool groups shown to agents via \`tools/list\`.
# Since each tool's full schema consumes ~80-150 tokens, only
# essential categories are included by default to save context.
#
# To add more tools for your agent, uncomment and extend:
#   toolCategories:
#     - navigation
#     - interaction
#     - dom
#     - smart
#     - ai
#     - diagnostic
#     - process
#     - terminal
#     - auth
#     - tabs
#     - devtools
#     - db          # ← Database tools (db_connect, db_query, etc.)
#     - storage     # ← Browser storage (cookies, localStorage, IndexedDB)
#     - debug       # ← Full debugger (breakpoints, step, variables)
#     - mobile      # ← Mobile/ADB tools (tap, swipe, logcat)
#     - recorder    # ← Test recording
#     - session     # ← Session management
#     - planner     # ← Planning/orchestration
#     - scheduler   # ← Workflow scheduling

browser:
  type: chromium
  headless: true
  defaultTimeout: 30000
  viewport:
    width: 1280
    height: 720

session:
  maxSessions: 10
  idleTimeoutSecs: 1800
  persistPath: ".fennec/sessions"

process:
  maxProcesses: 10
  logBufferLines: 2000
  spawnAllowlist:
    - "npm"
    - "node"
    - "pnpm"
    - "yarn"
    - "bun"
    - "python"
    - "python3"

terminal:
  logBufferLines: 2000
  watchDebounceMs: 50

network:
  bufferSize: 1000
  captureRequestBody: true
  captureResponseBody: true
  slowRequestThresholdMs: 1000

console:
  bufferSize: 500
  levels:
    - log
    - info
    - warn
    - error
    - debug

correlation:
  windowMs: 500
  enableRootCauseInference: true
  minConfidence: 0.7

security:
  sandbox: true
  allowProcessSpawn: true
  allowProcessKill: false
  allowedDomains: []
  blockedDomains: []
  allowFileProtocol: false
  allowCDPRawAccess: false
  exportPath: ".fennec/exports"
  maxExportSizeMB: 10

transport:
  type: stdio
  port: 3333
  host: "127.0.0.1"

logging:
  level: info
  format: pretty
  file: null
`;

  writeFileSync(configFile, config, 'utf-8');
  spinner.succeed(`Configuration written to ${pc.bold(configFile)}`);
  console.error(`\n  ${pc.dim('Edit the file to customize Fennec behavior.')}\n`);
}
