#!/usr/bin/env node

import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { intro, outro, spinner, confirm, select, isCancel } from "@clack/prompts";
import { FennecServer, SessionStore } from "@plumpslabs/fennec-core";
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { printBanner } from "./utils/banner.js";
import { showHelp } from "./utils/help.js";
import { pipeCommand } from "./commands/pipe.js";
import { attachPidCommand } from "./commands/attach-pid.js";
import { attachPortCommand } from "./commands/attach-port.js";
import { watchCommand } from "./commands/watch.js";

const [, , command, ...args] = process.argv;

async function main(): Promise<void> {
  if (!command || command === "start") {
    await startServer(args);
  } else if (command === "pipe") {
    await pipeCommand(args);
  } else if (command === "attach-pid") {
    await attachPidCommand(args);
  } else if (command === "attach-port") {
    await attachPortCommand(args);
  } else if (command === "watch") {
    await watchCommand(args);
  } else if (command === "sessions") {
    await sessionsCommand();
  } else if (command === "setup") {
    await setupCommand();
  } else if (command === "install-browsers") {
    printBanner();
    await installBrowsersCommand();
  } else if (command === "init") {
    printBanner();
    await initCommand();
  } else if (command === "help" || command === "--help" || command === "-h") {
    printBanner();
    showHelp();
  } else {
    console.error(`Unknown command: ${command}`);
    console.error("Run 'fennec help' for usage information");
    process.exit(1);
  }
}

async function startServer(args: string[]): Promise<void> {
  const configIndex = args.indexOf("--config");
  const configPath = configIndex !== -1 ? args[configIndex + 1] : undefined;
  const server = new FennecServer(configPath);
  await server.start();
}

async function sessionsCommand(): Promise<void> {
  const store = new SessionStore("./.fennec/sessions");
  const sessions = store.list();

  if (sessions.length === 0) {
    console.log("No saved sessions found.");
    return;
  }

  console.log("Saved sessions:");
  for (const s of sessions) {
    console.log(`  ${s.name} at ${s.origin} (saved: ${new Date(s.savedAt).toLocaleString()})`);
  }
  console.log(`\nTotal: ${sessions.length} session(s)`);
}

async function setupCommand(): Promise<void> {
  intro("Fennec Setup");

  const mcpClient = await select({
    message: "Which MCP client are you using?",
    options: [
      { value: "claude", label: "Claude Desktop" },
      { value: "other", label: "Other MCP client" },
    ],
  });

  if (isCancel(mcpClient)) {
    outro("Setup cancelled");
    return;
  }

  if (mcpClient === "claude") {
    console.log(`
To configure Claude Desktop for Fennec, add to your config:

{
  "mcpServers": {
    "fennec": {
      "command": "fennec",
      "args": ["start"]
    }
  }
}
    `);
  }

  outro("Setup complete! Run 'fennec start' to begin.");
}

async function installBrowsersCommand(): Promise<void> {
  intro("Installing browser engines");

  const s = spinner();
  s.start("Installing Chromium...");

  try {
    execSync("npx playwright install chromium", {
      stdio: "inherit",
      timeout: 120000,
    });
    s.stop("Chromium installed successfully");
  } catch {
    s.stop("Failed to install Chromium");
    console.error("Try running manually: npx playwright install chromium");
  }

  outro("Browser installation complete.");
}

async function initCommand(): Promise<void> {
  intro("Initialize Fennec Configuration");

  const configFile = resolve("./fennec.config.yaml");

  if (existsSync(configFile)) {
    const overwrite = await confirm({
      message: "fennec.config.yaml already exists. Overwrite?",
    });

    if (isCancel(overwrite) || !overwrite) {
      outro("Cancelled");
      return;
    }
  }

  const config = `# Fennec Configuration
# Generated by 'fennec init'

browser:
  type: chromium
  headless: true
  defaultTimeout: 30000
  viewport:
    width: 1280
    height: 720

session:
  maxSessions: 10
  idleTimeoutSecs: 1800
  persistPath: "./.fennec/sessions"

process:
  maxProcesses: 10
  logBufferLines: 2000
  spawnAllowlist:
    - "npm"
    - "node"
    - "pnpm"
    - "yarn"
    - "bun"
    - "python"
    - "python3"

terminal:
  logBufferLines: 2000
  watchDebounceMs: 50

network:
  bufferSize: 1000
  captureRequestBody: true
  captureResponseBody: true
  slowRequestThresholdMs: 1000

console:
  bufferSize: 500
  levels:
    - log
    - info
    - warn
    - error
    - debug

correlation:
  windowMs: 500
  enableRootCauseInference: true
  minConfidence: 0.7

security:
  sandbox: true
  allowProcessSpawn: true
  allowProcessKill: false
  allowedDomains: []
  blockedDomains: []
  allowFileProtocol: false
  allowCDPRawAccess: false
  exportPath: "./.fennec/exports"
  maxExportSizeMB: 10

transport:
  type: stdio
  port: 3333
  host: "127.0.0.1"

logging:
  level: info
  format: pretty
  file: null
`;

  writeFileSync(configFile, config, "utf-8");
  outro(`Configuration written to ${configFile}`);
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
